NawafizApp.Web/Controllers/AuctionController.cs
using NawafizApp.Services.Dtos;

using NawafizApp.Services.Identity;
using NawafizApp.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NawafizApp.Common;
using Microsoft.AspNet.Identity;

using NawafizApp.Web.Models;

namespace NawafizApp.Web.Controllers
{
    public class AuctionController : BaseAuthorizeController
    {
        IAuctionService _IAuctionService;
        public AuctionController(ApplicationUserManager userManager, ApplicationSignInManager signInManager,IAuctionService ias) : base(userManager, signInManager)
        {
            this._IAuctionService = ias;
        }

        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Roles ="Admin")]
        public ActionResult AddLocation()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddLocation(LocationDto dto)
        {
            _IAuctionService.addLocation(dto);
            return RedirectToAction("AddLocation");
        }
        public ActionResult getAllLocations()
        {
            return View(_IAuctionService.getAllLocations());
        }
        [Authorize(Roles = "Admin")]
        public ActionResult EditLocation(int id)
        {

            return View(_IAuctionService.getLocationById(id));
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditLocation(int id,LocationDto dto)
        {
            var x = _IAuctionService.EditLocation(id, dto);

            return RedirectToAction("AddLocation");
        }
        [Authorize(Roles ="Admin")]
        public ActionResult DeleteLocation (int id)
        {
            _IAuctionService.deleteLocation(id);
            return RedirectToAction("AddLocation");

        }

        [Authorize(Roles = "Admin")]
        public ActionResult AddDecoration()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddDecoration(DecorationDto dto)
        {
            _IAuctionService.addDecoration(dto);
            return RedirectToAction("AddDecoration");
        }
        [Authorize(Roles = "Admin")]
        public ActionResult getAllDecorations()
        {
            return View(_IAuctionService.getAllDecorations());
        }

        [Authorize(Roles = "Admin")]
        public ActionResult EditDecoration(int id)
        {

            return View(_IAuctionService.getDecorationById(id));
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditDecoration(int id, DecorationDto dto)
        {
            var x = _IAuctionService.EditDecoration(id, dto);

            return RedirectToAction("AddDecoration");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult DeleteDecoration(int id)
        {
            _IAuctionService.deleteDecoration(id);
            return RedirectToAction("AddDecoration");

        }

        [Authorize(Roles = "Admin")]
        public ActionResult AddFloor()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddFloor(FloorDto dto)
        {
            _IAuctionService.addFloor(dto);
            return RedirectToAction("AddFloor");
        }
        [Authorize(Roles = "Admin")]
        public ActionResult getAllFloors()
        {
            return View(_IAuctionService.getAllFloors());
        }

        [Authorize(Roles = "Admin")]
        public ActionResult EditFloor(int id)
        {

            return View(_IAuctionService.getFloorById(id));
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditFloor(int id, FloorDto dto)
        {
            var x = _IAuctionService.EditFloor(id, dto);

            return RedirectToAction("AddFloor");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult DeleteFloor(int id)
        {
            _IAuctionService.deleteFloor(id);
            return RedirectToAction("AddFloor");

        }

        [Authorize(Roles = "Admin")]
        public ActionResult AddDirection()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddDirection(DirectionDto dto)
        {
            _IAuctionService.addDirection(dto);
            return RedirectToAction("AddDirection");
        }
        [Authorize(Roles = "Admin")]
        public ActionResult getAllDirections()
        {
            return View(_IAuctionService.getAllDirections());
        }

        [Authorize(Roles = "Admin")]
        public ActionResult EditDirection(int id)
        {

            return View(_IAuctionService.getDirectionById(id));
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditDirection(int id, DirectionDto dto)
        {
            var x = _IAuctionService.EditDirection(id, dto);

            return RedirectToAction("AddDirection");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult DeleteDirection(int id)
        {
            _IAuctionService.deleteDirection(id);
            return RedirectToAction("AddDirection");

        }

        [Authorize(Roles = "Admin")]
        public ActionResult AddH_View()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddH_View(H_ViewDto dto)
        {
            _IAuctionService.addH_View(dto);
            return RedirectToAction("AddH_View");
        }
        [Authorize(Roles = "Admin")]
        public ActionResult getAllH_Views()
        {
            return View(_IAuctionService.getAllH_Views());
        }

        [Authorize(Roles = "Admin")]
        public ActionResult EditH_View(int id)
        {

            return View(_IAuctionService.getH_ViewById(id));
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditH_View(int id, H_ViewDto dto)
        {
            var x = _IAuctionService.EditH_View(id, dto);

            return RedirectToAction("AddH_View");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult DeleteH_View(int id)
        {
            _IAuctionService.deleteH_View(id);
            return RedirectToAction("AddH_View");

        }
        [Authorize]
        public ActionResult getActiveAuctions()
        {
            return View(_IAuctionService.getActiveAuctions());
        }

        [Authorize]
        public ActionResult getAuction(int id)
        {
            bool t = _IAuctionService.checkIfAuctionStillAvailable(id);
            AuctionDeatailsDto dto = _IAuctionService.getAuctionById(id);
            ViewBag.check = t;
            if (!t)
            {
                ViewBag.w = _IAuctionService.getCurrentBidAndBider(id).currentBider;
                ViewBag.b = _IAuctionService.getCurrentBidAndBider(id).currentBid;
              
            }
            ViewBag.owner = false;
            var currentUserId = getGuid(User.Identity.GetUserId());
            if(currentUserId == dto.OwnerId)
            {
                ViewBag.owner = true;
            }
           
            
            return View(dto);
           // return RedirectToAction("expired" ,new { id = id});
        }

        [Authorize]
        public ActionResult expired(int id)
        {
            if(!_IAuctionService.checkIfAuctionStillAvailable(id))
                return View();
            return RedirectToAction("getAuction", new { id = id });
       
        }
        [Authorize]
        public ActionResult getCurrent(int id)
        {
            if (Request.IsAjaxRequest())
            {
             //   if(_IAuctionService.checkIfAuctionStillAvailable(id))
                return PartialView(_IAuctionService.getCurrentBidAndBider(id));
                

            }
            return PartialView(_IAuctionService.getCurrentBidAndBider(id));
        }
        [Authorize]
        public ActionResult myAuctions()
        {
            var id = getGuid(User.Identity.GetUserId());
            return View(_IAuctionService.getMyAuctions(id));
        }
        [Authorize]
        public ActionResult myActions()
        {
            var id = getGuid(User.Identity.GetUserId());
            return View(_IAuctionService.getMyActions(id));
        }
        [Authorize]
        public ActionResult Bid (int auId,int val)
        {
            if(Request.IsAjaxRequest())
            {
                if (!_IAuctionService.checkIfAuctionStillAvailable(auId))
                {
                    ViewBag.mess = "انتهى المزاد";
                    return PartialView();
                }
                    var id = getGuid(User.Identity.GetUserId());
                ViewBag.mess = _IAuctionService.bid(auId, val, id);
                return PartialView();
            }
            return PartialView();
        }
        [Authorize]
        public ActionResult addAuction()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult addAuction(AddAuctionDto dto,IEnumerable<HttpPostedFileBase> files)
        {
            ViewBag.error = "";
            DateTime date1 = DateTime.MaxValue ;
            DateTime date2 = DateTime.MaxValue;
            TimeSpan time1 = TimeSpan.MaxValue;
            TimeSpan time2 = TimeSpan.MaxValue ;
            try
            {

NawafizApp.Web/Views/Auction/AddDecoration.cshtml
@model NawafizApp.Services.Dtos.DecorationDto
<style>
    a {
        text-shadow: none;
        color: #afab14;
    }
</style>
<div class="portlet box yellow">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-diamond"></i>الديكورات
        </div>
    </div>
    <div class="portlet-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.Label("النمط", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.type, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-xs-offset-2 col-md-2 col-xs-9 col-sm-2">
                        <input type="submit" value="إضافة" class="btn btn-warning" style="width:100%" />
                    </div>
                </div>
            </div>
        }
        <div style="margin-top:5%;">
            @{ Html.RenderAction("getAllDecorations");

            }
        </div>
    </div>
</div>

NawafizApp.Web/Views/Auction/AddDirection.cshtml
@model NawafizApp.Services.Dtos.DirectionDto

<style>
    a {
        text-shadow: none;
        color: #afab14;
    }
</style>
<div class="portlet box yellow">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-cc-discover"></i>الاتجاهات
        </div>
    </div>
    <div class="portlet-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.Label("الاسم", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-xs-offset-2 col-md-2 col-xs-9 col-sm-2">
                        <input type="submit" value="إضافة" class="btn btn-warning" style="width:100%" />
                    </div>
                </div>
            </div>
        }
        <div style="margin-top:5%;">
            @{ Html.RenderAction("getAllDirections");

            }
        </div>
    </div>
</div>

NawafizApp.Web/Views/Auction/AddFloor.cshtml
@model NawafizApp.Services.Dtos.FloorDto

<style>
    a {
        text-shadow: none;
        color: #afab14;
    }
</style>
<div class="portlet box yellow">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-building"></i>الطوابق
        </div>
    </div>
    <div class="portlet-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.Label("الطابق", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.number, new { htmlAttributes = new { @class = "form-control", autocomplete = "off",@type="number" } })
                        @Html.ValidationMessageFor(model => model.number, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-xs-offset-2 col-md-2 col-xs-9 col-sm-2">
                        <input type="submit" value="إضافة" class="btn btn-warning" style="width:100%" />
                    </div>
                </div>
            </div>
        }
        <div style="margin-top:5%;">
            @{ Html.RenderAction("getAllFloors");

            }
        </div>
    </div>
</div>

NawafizApp.Web/Views/Auction/EditDecoration.cshtml
@model NawafizApp.Services.Dtos.DecorationDto

<div class="portlet box yellow">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-location-arrow"></i>تعديل الديكور
        </div>
    </div>
    <div class="portlet-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.Label("النمط", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.type, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-xs-offset-2 col-md-2 col-xs-9 col-sm-2">
                        <input type="submit" value="حفظ البيانات" class="btn btn-warning" style="width:100%" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>

NawafizApp.Web/Views/Auction/EditDirection.cshtml
@model NawafizApp.Services.Dtos.DirectionDto
<div class="portlet box yellow">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-location-arrow"></i>تعديل الاتجاه
        </div>
    </div>
    <div class="portlet-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.Label("الاسم", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-xs-offset-2 col-md-2 col-xs-9 col-sm-2">
                        <input type="submit" value="حفظ البيانات" class="btn btn-warning" style="width:100%" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>

NawafizApp.Web/Views/Auction/EditFloor.cshtml
@model NawafizApp.Services.Dtos.FloorDto
<div class="portlet box yellow">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-location-arrow"></i>تعديل الطابق
        </div>
    </div>
    <div class="portlet-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.Label("الطابق", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.number, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.number, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-xs-offset-2 col-md-2 col-xs-9 col-sm-2">
                        <input type="submit" value="حفظ البيانات" class="btn btn-warning" style="width:100%" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>

NawafizApp.Web/Views/Auction/EditLocation.cshtml
@model NawafizApp.Services.Dtos.LocationDto

<div class="portlet box yellow">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-location-arrow"></i>تعديل الموقع
        </div>
    </div>
    <div class="portlet-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.Label("الاسم", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-xs-offset-2 col-md-2 col-xs-9 col-sm-2">
                        <input type="submit" value="حفظ البيانات" class="btn btn-warning" style="width:100%" />
                    </div>
                </div>
            </div>
        }
     
    </div>
</div>

NawafizApp.Web/Views/Auction/addAuction.cshtml
@model NawafizApp.Services.Dtos.AddAuctionDto
    @using NawafizApp.Web.Models
<div class="container-fluid">
    @using (Html.BeginForm("addAuction", "Auction", FormMethod.Post, new
    {
        @enctype = "multipart/form-data"

    }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>إضافة مزاد</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <h2 class="text-danger">@ViewBag.error</h2>

            <div class="row">
                <div class="form-group col-md-6">
                    <label class="control-label col-md-4"> تاريخ البداية </label>
                    <div class="col-md-8">
                        <div style="position:relative;margin-bottom:10px">
                            <input autocomplete="off" name="startDate" id="dd" class="form-control date-picker" data-date-format="dd/mm/yyyy" type="text" value="">
                            <span id="fup" class="error" style="display:none;color:#ed6b75;position:absolute;bottom:-19px;right:0">تاريخ بداية العرض مطلوب</span>
                        </div>

                    </div>
                </div>
                <div class="form-group col-md-6">
                    <label class="control-label col-md-4">وقت البداية</label>
                    <div class="col-md-8">
                        <div class="input-group">

                            @Html.EditorFor(model => model.strTime, new { htmlAttributes = new { @class = "form-control timepicker timepicker-no-seconds", autocomplete = "off", @id = "starts" } })
                            <span class="input-group-btn">
                                <button class="btn default" type="button">
                                    <i class="fa fa-clock-o"></i>
                                </button>

                            </span>
                        </div>
                        @Html.ValidationMessageFor(model => model.strTime, "", new { @class = "text-danger" })
                    </div>

                </div>
            </div>
            <div class="row">

                <div class="form-group col-md-6">
                    <label class="control-label col-md-4"> تاريخ النهاية </label>
                    <div class="col-md-8">
                        <div style="position:relative;margin-bottom:10px">
                            <input autocomplete="off" name="endDate" id="dd" class="form-control date-picker" data-date-format="dd/mm/yyyy" type="text" value="">
                            <span id="fup" class="error" style="display:none;color:#ed6b75;position:absolute;bottom:-19px;right:0">تاريخ بداية العرض مطلوب</span>
                        </div>

                    </div>
                </div>
                <div class="form-group col-md-6">
                    <label class="control-label col-md-4">وقت النهاية</label>
                    <div class="col-md-8">
                        <div class="input-group">

                            @Html.EditorFor(model => model.EndTimeTime, new { htmlAttributes = new { @class = "form-control timepicker timepicker-no-seconds", autocomplete = "off", @id = "starts" } })
                            <span class="input-group-btn">
                                <button class="btn default" type="button">
                                    <i class="fa fa-clock-o"></i>
                                </button>

                            </span>
                        </div>
                        @Html.ValidationMessageFor(model => model.EndTimeTime, "", new { @class = "text-danger" })
                    </div>

                </div>
            </div>





            <div class="row">
                

                <div class="form-group col-md-6">
                    @Html.Label("المساحة", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.size, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.size, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    @Html.Label("الاتجاه1", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.Direction1, SelectsHelper.Directions(null), new { @class = "form-control", id = "list169" })
                        @Html.ValidationMessageFor(model => model.Direction1, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-6">
                    @Html.Label("الاتجاه2", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.Direction2, SelectsHelper.Directions(null), new { @class = "form-control", id = "list145" })
                        @Html.ValidationMessageFor(model => model.Direction2, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    @Html.Label("الاتجاه3", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.Direction3, SelectsHelper.Directions(null), new { @class = "form-control", id = "list111" })
                        @Html.ValidationMessageFor(model => model.Direction3, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-6">

                    @Html.Label("الاتجاه4", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.Direction4, SelectsHelper.Directions(null), new { @class = "form-control", id = "list12" })
                        @Html.ValidationMessageFor(model => model.Direction4, "", new { @class = "text-danger" })
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">

                    @Html.Label("الموقع", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.locationId, SelectsHelper.Locations(null), new { @class = "form-control", id = "list1" })
                        @Html.ValidationMessageFor(model => model.locationId, "", new { @class = "text-danger" })
                    </div>

                </div>

                <div class="form-group col-md-6">

                    @Html.Label("الإطلالة", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.h_ViewId, SelectsHelper.H_Views(null), new { @class = "form-control", id = "list2" })
                        @Html.ValidationMessageFor(model => model.h_ViewId, "", new { @class = "text-danger" })
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">

                    @Html.Label("الطابق", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.floorId, SelectsHelper.Floors(null), new { @class = "form-control", id = "list1" })
                        @Html.ValidationMessageFor(model => model.floorId, "", new { @class = "text-danger" })
                    </div>

                </div>

                <div class="form-group col-md-6">

                    @Html.Label("الديكور", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.decorationId, SelectsHelper.Decorations(null), new { @class = "form-control", id = "list188" })
                        @Html.ValidationMessageFor(model => model.decorationId, "", new { @class = "text-danger" })
                    </div>

                </div>
            </div>
            <div class="form-group">
                @Html.Label(" الصور", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="btn btn-default image-preview-input">
                        <span class="glyphicon glyphicon-folder-open"></span>
                        <span class="image-preview-input-title">قم بتحديد عدة ملفات</span>
                        <input type="file" accept="image/png, image/jpeg, image/gif" name="files" id="fileEn" multiple />
                    </div>

                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="إضافة" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>
<script src="~/Scripts/jquery-3.1.1.js"></script>
<script>
    $("#list1").change(function () {

        $.ajax({
            type: 'post',
            url: '@Url.Action("getconvinientViews", "Auction")',
            data: { lId: $("#list1").val() },
            success: function (data) {
                
                // var ddldist2 = $('#listbox').parent().children().last();
                var ddldist = $('#list2');
            
                if (data.length == 0) {
                    //ddldist.html("");// ddldist2.html("");
                    ddldist.empty();



                }
                else {


                    ddldist.empty();

                    $.each(data, function (Val, Text) {
                        //      alert(this.Text);

                        //  alert(this.Text);
                        ddldist.append(
                            $('<option></option>').val(this.Value).html(this.Text)
                        );

                    });







                }

            }
        });
    });

</script>

NawafizApp.Web/Views/Auction/expired.cshtml
<h3>انتهى المزاد  </h3>